version: "2"

services:
  server:
    image: "server"
    ports:
      - "8090:8090"
    container_name: "server"

  front:
    image: "front"
    ports:
      - "3000:3000"
    container_name: "front"
